### ISSUE TITLE
Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by maulikgateway** [v4l3r10/node-cache-manager-mongodb#1]
I copied pasted given code for Single store and tried to run uit but it gives an error that "Cannot read property 'update' of undefined".
Can anyone help to to identify what's wrong?

**Comment by psycomp** [comment]
I have the same problem.

**Comment by angelxmoreno** [comment]
similar issue

**Comment by angelxmoreno** [comment]
found the issue and opened #2
