### ISSUE TITLE
Throws an error if the collection exists

### ISSUE THREAD

**Issue by vladimir-trifonov** [v4l3r10/node-cache-manager-mongodb#17]

**Comment by yalshamy** [comment]
your need to install the package from github not form npm because I found this bug fixed it github but created relases with this fix 
`npm install --save https://github.com/v4l3r10/node-cache-manager-mongodb.git`

**Comment by schursin** [comment]
> your need to install the package from github not form npm because I found this bug fixed it github but created relases with this fix
> `npm install --save https://github.com/v4l3r10/node-cache-manager-mongodb.git`

release coming soon?

**Comment by cxn-pszakacs** [comment]
@v4l3r10  Please release this fix to npm.
Thanks!

**Comment by v4l3r10** [comment]
Done!
