### ISSUE TITLE
Race conditions making `store.collection` undefined

### ISSUE THREAD

**Issue by angelxmoreno** [v4l3r10/node-cache-manager-mongodb#2]
After some testing, I have concluded that there is a race condition when cache-manager checks the store using this driver.

The solution would be to use something like the `async` lib to ensure a connection is made prior to cache-manager trying to get, set, etc.

**Comment by v4l3r10** [comment]
Thank you for checks!

i write a fix soon.

**Comment by v4l3r10** [comment]
fixed in last commit

**Comment by maissani** [comment]
@v4l3r10 Can you tag and publish it to Npm ?

**Comment by guillaumev** [comment]
@v4l3r10 Would it be possible to have a fixed 0.1.7 version soon ? Really need it for my project... :-)

**Comment by v4l3r10** [comment]
I am sorry for the delay!
new 0.1.7 up (https://github.com/v4l3r10/node-cache-manager-mongodb/commit/5b8e64fbac8f075a52b2a357b9e69fb3e35685bb)

I'm working on new cache-manager 2.x feature.

**Comment by guillaumev** [comment]
Thank you :-) !
