### ISSUE TITLE
expiring in mongo is broken

### ISSUE THREAD

**Issue by dcolens** [v4l3r10/node-cache-manager-mongodb#5]
the code correctly creates an index to have mongo automatically clear expired entries at:
https://github.com/v4l3r10/node-cache-manager-mongodb/blob/ba2b87313590a6a510e11602535f124bd9cec00f/index.js#L71

But the data stored in Mongo is wrong for 2 reasons:
1) the key used is "expire" instead of "expireAt"
2) the value saved is an integer instead of a Date object
Ref: https://github.com/v4l3r10/node-cache-manager-mongodb/blob/master/index.js#L202

This can lead to real bad db leakage. The https://github.com/disjunction/node-cache-manager-mongoose project seem to handle it better (comment based on code inspection, I did not try it yet).

**Comment by v4l3r10** [comment]
Good point!
i check and fix it tomorrow.

thx for report. :smile:

**Comment by dcolens** [comment]
FYI, I forked and wrote a fix at https://github.com/dcolens/node-cache-manager-mongodb/commit/70456af4dcd79ec7b7250276ba0b4d68883aac3c I also added tests (require a mongo on localhost, but you could enable travis-ci to run them)

**Comment by bonesoul** [comment]
when this well fixed in?

**Comment by v4l3r10** [comment]
@dcolens please post a pull request with ur fix,,  i merge it soon.

**Comment by jaumard** [comment]
Right, after some tests yeah data are broken because of this :(

**Comment by TheBeastLT** [comment]
Any news on this? The expiring is not working and I'm getting `The field 'expiresAt' is not valid for an index specification.` error after debugging the connection.

**Comment by v4l3r10** [comment]
fixed in new release. sorry for delay
