### ISSUE TITLE
[TALK] TTL vs ExpireAt field

### ISSUE THREAD

**Issue by v4l3r10** [v4l3r10/node-cache-manager-mongodb#9]
I think that is useful to talk about two way "expire" system. 
On old MongoDb without TTL feature, the only way is to use ExpireAt + Date check on fetch. 
So the question is, we want to keep old Mongo compatibility or switch full to new TTL?

**Comment by jaumard** [comment]
I'll say that if it's easily doable it's nice to keep retro compatibility but if it's complicated or not maintainable then better to go to full new TTL :)
That's my opinion, but I'll only use the new versions of mongo  ^^

**Comment by jaumard** [comment]
Any news on this ?

**Comment by v4l3r10** [comment]
fixed in new release. sorry for delay.
